### ISSUE TITLE
Jak použít tyto materiály?

### ISSUE THREAD

**Issue by honzajavorek** [ondrej-hosak/JakPsatSQL#38]
Ahoj, mám tyto materiály k SQL dlouho v záložkách, že se na ně podívám a případně budu doporučovat lidem, kteří se chtějí SQL naučit. Teď na to koukám, ale není mi jasné, jak se mají použít. V README je postup k instalaci, ale chybí mi vysvětlení nějakého konceptu, jak se očekává, že s tím člověk pracuje, apod. Má si to samouk stáhnout a nainstalovat k sobě? Nebo to má nějakou webovku, kde může přímo zkoušet?

**Comment by ondrej-hosak** [comment]
Ahoj, o jake materialy se jedna? Muzem je zaradit do samostatne zalozky na https://kacenka.fun/#/home

**Comment by honzajavorek** [comment]
Aha :) Měl jsem za to, že Jak psát SQL jsou nějaké materiály k naučení se SQL, nebo web, kde se to dá naučit, který se používá v Czechitas, ale dal by se doporučovat i začátečníkům samoukům, kteří se chtějí SQL naučit (podobně jako https://github.com/pyvec/naucse.python.cz, které je na https://naucse.python.cz/). Možná jsem jen špatně pochopil účel projektu, nebo se v tom zatím neorientuji. A issue jsem založil proto, abych se vlastně zorientoval 😄

**Comment by ondrej-hosak** [comment]
Ucel jsi pochopil spravne, je to pro vyuku SQL v Czechitas. Nicmene o sekci pro samouky jsme zatim neuvazovali, ale myslim, ze by nebyl problem je zridit. Co myslis @pavel242242 ?

**Comment by chocholous** [comment]
jj, web je dostupny na https://jakpsatsql.cz, nebo na https://selektuju.cz / https://kacenka.fun.
pro samouky to uplne vhodny neni, chybi nam tam sekce naliti dat, nad kteryma ta vyuka probiha (pripadne vydani loginu do snowflake/azure, kde uz data jsou)
ted zrovna probiha velika predelavka materialu, proto mame dve zalozky vyuka, kde jedna je ta stara jenom snowflakova, a druha uz v sobe obsahuje lekce pro azure a snowflake zvlast. Taky pridavame rozcleneni lekci na DA Data, Data Girls a SQL 1,2,3, coz jsou tri formaty vyuky SQL v czechitas.

**Comment by honzajavorek** [comment]
Jasan, díky, teď už tomu rozumím lépe. Z README nebo pravého sloupce nebyl odkaz ani na ty adresy. Je super, že to děláte Open Source a třeba až se to ustálí, tak se povede to doplnit i o ty věci pro samouky. Bez toho se materiály nedají dál doporučit (nemá se z nich jak mimo Czechitas učit) a to je vlastně škoda, když už otevřeně vznikají.

Dík moc za odpovědi, budu to tady po očku dál sledovat. SQL zdar!
